# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e70716cae66c0a4bdc067d843ae5d23e1e8c6e6991b691c5c20e2440453eb5ed1c2a650bcaf18739b5a8bcbede3eaeda1d8a2f12a80cfe5b92ce44de2f343f1

test:
  secret_key_base: 00811195b8c37df4b8bf7959354dbd56300bec717c824fbe2441c86e341c85c3ce24a8a15b19f5ce393aa3023007e4087981b5a2726e55e14d062be37385bf59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
